import { useMemo } from 'react'
import { useNavigate } from 'react-router-dom'
import { useRxRecs, useTradePositions, useWatchlist, type RxRecListItem } from '../hooks/use-api'
import { Skeleton } from '../components/ui/skeleton'
import { Stethoscope } from 'lucide-react'
import { DriftBar } from '../components/charts/svg/DriftBar'
import { StatusBadge } from '../components/common/StatusBadge'
import { PageHeader } from '../components/common/PageHeader'
import { PageWithSidecar } from '../components/common/DetailSidecar'
import { RecsSidecar } from '../components/rx/RecsSidecar'
import { RecCard, RX_STATUS_BAR_BG } from '../components/rx/RecRow'

function relTime(iso: string): string {
  const now = Date.now()
  const t = new Date(iso).getTime()
  const ago = Math.max(0, now - t)
  const min = Math.floor(ago / 60_000)
  if (min < 1) return 'just now'
  if (min < 60) return `${min}m ago`
  const hr = Math.floor(min / 60)
  if (hr < 24) return `${hr}h ago`
  const d = Math.floor(hr / 24)
  return `${d}d ago`
}

function recStatusValue(it: RxRecListItem): string {
  if (it.status === 'snoozed' && it.auto_revived) return 'auto_revived'
  return it.status
}

// Same ticker noise denylist as the rec detail page + backend service.
const TICKER_NOISE_DENYLIST = new Set([
  'AI', 'API', 'BUY', 'CEO', 'CFO', 'CPI', 'CPU', 'DCF', 'EBIT', 'EBITDA',
  'EOD', 'ETF', 'FAQ', 'FED', 'FOMC', 'GDP', 'GPU', 'HOLD', 'IPO', 'IRR',
  'LBO', 'MA', 'OPEN', 'OTC', 'PE', 'PMI', 'ROI', 'RSI', 'SELL', 'SP',
  'SPX', 'SP500', 'SPY', 'TBD', 'TLDR', 'UK', 'US', 'USA', 'VIX', 'WSJ',
  'YOY', 'YTD',
])

function guessTicker(tldr: string | null | undefined): string | null {
  if (!tldr) return null
  const matches = tldr.match(/\b[A-Z]{2,5}\b/g) ?? []
  for (const m of matches) if (!TICKER_NOISE_DENYLIST.has(m)) return m
  return null
}

// Heuristic conflict detector: rec mentions "trim"/"close"/"sell"/"short"
// on a ticker the operator is long; OR "add"/"buy"/"long" on a ticker
// they're already heavy in.
function detectConflict(tldr: string | null | undefined, holdsLong: boolean): boolean {
  if (!holdsLong || !tldr) return false
  const lower = tldr.toLowerCase()
  return /\b(trim|close|sell|short|dump|exit)\b/.test(lower)
}

export function RxFinance() {
  const navigate = useNavigate()
  const recs = useRxRecs({ window_days: 60, limit: 200 })
  const positions = useTradePositions({ limit: 200 })
  const watchlist = useWatchlist({ limit: 500 })

  const annotated = useMemo(() => {
    const positionTickers = new Set(
      (positions.data?.items ?? []).filter((p) => p.qty > 0).map((p) => p.ticker),
    )
    const watchlistTickers = new Set(
      (watchlist.data?.items ?? []).map((w: any) => (w.symbol || w.ticker || '').toUpperCase()),
    )
    return (recs.data?.items ?? []).map((rec) => {
      const ticker = guessTicker(rec.tldr_short)
      const inPosition = ticker ? positionTickers.has(ticker) : false
      const inWatchlist = ticker ? watchlistTickers.has(ticker) : false
      const conflict = detectConflict(rec.tldr_short, inPosition)
      return { rec, annot: { ticker, inPosition, inWatchlist, conflict } }
    })
  }, [recs.data, positions.data, watchlist.data])

  // Default sort: forced > aging > conflicts > drift.
  const sortedAnnotated = useMemo(() => {
    return [...annotated].sort((a, b) => {
      if (a.rec.forced_decision !== b.rec.forced_decision) return a.rec.forced_decision ? -1 : 1
      if (a.rec.aging !== b.rec.aging) return a.rec.aging ? -1 : 1
      if (a.annot.conflict !== b.annot.conflict) return a.annot.conflict ? -1 : 1
      return (b.rec.drift_score ?? 0) - (a.rec.drift_score ?? 0)
    })
  }, [annotated])

  const main = (
    <div className="space-y-4">
      <PageHeader
        icon={Stethoscope}
        title="Finance recommendations"
        description={
          <>Generated by Claude Code <code className="text-xs">/rx-finance</code>. Disposition here syncs back to Lakshmi markdown on next run.</>
        }
      />

      {recs.isLoading ? (
        <Skeleton className="h-40 w-full" />
      ) : sortedAnnotated.length === 0 ? (
        <div className="rounded-3xl shadow-inset-sm p-8 text-center text-muted-foreground bg-background">
          <Stethoscope className="h-8 w-8 mb-2 mx-auto text-muted-foreground/50" />
          <p className="text-sm">No finance recs in the last 60 days.</p>
          <p className="text-xs mt-2">Run <code>/rx-finance</code> on the laptop to generate one.</p>
        </div>
      ) : (
        <>
          {/* Mobile: stacked card list */}
          <div className="md:hidden space-y-3">
            {sortedAnnotated.map(({ rec, annot }) => (
              <RecCard key={rec.id} rec={rec} annot={annot} />
            ))}
          </div>
          {/* Desktop: table with Context column for conflict/position/watchlist signal */}
          <div className="hidden md:block rounded-2xl bg-background shadow-inset-sm p-3 overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr>
                  <th className="text-left px-3 py-2 text-xs font-semibold text-muted-foreground">ID</th>
                  <th className="text-left px-3 py-2 text-xs font-semibold text-muted-foreground">When</th>
                  <th className="text-left px-3 py-2 text-xs font-semibold text-muted-foreground">Drift</th>
                  <th className="text-right px-3 py-2 text-xs font-semibold text-muted-foreground">Conf</th>
                  <th className="text-left px-3 py-2 text-xs font-semibold text-muted-foreground">Status</th>
                  <th className="text-left px-3 py-2 text-xs font-semibold text-muted-foreground">TLDR</th>
                  <th className="text-left px-3 py-2 text-xs font-semibold text-muted-foreground">Context</th>
                  <th className="text-left px-3 py-2 text-xs font-semibold text-muted-foreground">Flags</th>
                </tr>
              </thead>
              <tbody>
                {sortedAnnotated.map(({ rec: it, annot }) => {
                  const barClass = RX_STATUS_BAR_BG[recStatusValue(it)] ?? 'bg-muted-foreground/30'
                  return (
                  <tr
                    key={it.id}
                    className="border-t border-border/40 hover:bg-muted/40 cursor-pointer"
                    onClick={() => navigate(`/motion/recs/${it.id}`)}
                  >
                    <td className="px-3 py-2 font-mono text-xs relative">
                      <div
                        aria-hidden
                        className={`absolute left-0 top-1.5 bottom-1.5 w-[3px] rounded-r ${barClass}`}
                      />
                      <span className="pl-1.5 inline-block">{it.short_id}</span>
                    </td>
                    <td className="px-3 py-2 text-xs whitespace-nowrap tabular-nums">{relTime(it.created_at)}</td>
                    <td className="px-3 py-2"><DriftBar score={it.drift_score} size="md" /></td>
                    <td className="px-3 py-2 text-right tabular-nums">{it.confidence ?? '—'}</td>
                    <td className="px-3 py-2"><StatusBadge kind="rec" value={recStatusValue(it)} /></td>
                    <td className="px-3 py-2 text-xs">
                      {it.tldr_short || <span className="text-muted-foreground">—</span>}
                    </td>
                    <td className="px-3 py-2">
                      <div className="flex flex-col gap-0.5 text-xs">
                        {annot.inPosition && (
                          <span className="text-primary font-semibold">in position</span>
                        )}
                        {annot.inWatchlist && !annot.inPosition && (
                          <span className="text-muted-foreground">on watchlist</span>
                        )}
                        {!annot.ticker && (
                          <span className="text-muted-foreground/60">—</span>
                        )}
                      </div>
                    </td>
                    <td className="px-3 py-2 space-x-1">
                      {annot.conflict && <StatusBadge kind="flag" value="conflict" size="xs" />}
                      {it.aging && <StatusBadge kind="flag" value="aging" size="xs" />}
                      {it.forced_decision && <StatusBadge kind="flag" value="forced" size="xs" />}
                    </td>
                  </tr>
                  )
                })}
              </tbody>
            </table>
          </div>
        </>
      )}
    </div>
  )

  return <PageWithSidecar main={main} sidecar={<RecsSidecar />} />
}
